Feature/cli/support
pylover/chttpd pull request #4
Opened 2023-07-22 08:45 UTC by hosseinsokhandan

2023-07-22 08:46 UTC, hosseinsokhandan commented on chttpd.c
> +        bind_addr_arg = "127.0.0.1";
@pylover please ensure it is good enough to only convert `localhost` to its relevant IP address.

2023-07-22 08:57 UTC, pylover commented
I preffer the title: `Feature: CLI -b/--bind and -p/--port`

2023-07-22 08:57 UTC, pylover requested changes

2023-07-22 08:57 UTC, pylover commented on chttpd.c
> +#include <getopt.h>
As told you before, use `GNU ARGP`

2023-07-22 08:59 UTC, pylover commented
https://www.gnu.org/software/libc/manual/html_node/Argp.html

2023-08-13 08:54 UTC, pylover approved these changes

2023-08-13 08:55 UTC, merged